version: '3.8'

services:
  postgres:
    container_name: db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432"

  backend:
    container_name: backend
    build: 
      context: ./blp-be
      dockerfile: Dockerfile
    env_file:
      - .env
    # environment:
    #   - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    #   - NODE_ENV=production
    #   - PORT=3000
    #   # Add other environment variables as needed
    ports:
      - "3000"
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build:
      context: ./blp-fe
      dockerfile: Dockerfile
    env_file:
      - .env
    #   # Add other environment variables as needed
    ports:
      - "8000"
    depends_on:
      - backend
    links:
      - backend

volumes:
  postgres_data:
